name = "MecaPluto"
uuid = "abacf8e0-d799-4236-b01a-c9dfe35432fc"
authors = ["Bart Janssens <bart@bartjanssens.org>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
